language: csharp
solution: CgiApiRework.sln
mono: none
dotnet: 2.0.0
before_install:
- openssl aes-256-cbc -K $encrypted_45d6741a46dd_key -iv $encrypted_45d6741a46dd_iv
  -in appsettings.json.enc -out CgiApiRework/appsettings.json -d
install:
- dotnet restore
script:
 - dotnet build
